version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=armario

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db/armario

    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
